name: CI - Build JAR

on:
  push:
    branches: [ "**" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v2

      - name: Set up Gradle (cache)
        uses: gradle/actions/setup-gradle@v3

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build (skip tests)
        run: ./gradlew clean build -x test

      - name: Upload JAR artifacts
        uses: actions/upload-artifact@v4
        with:
          name: jars
          path: |
            **/build/libs/*.jar
          if-no-files-found: error
